### ISSUE TITLE
Crash after onActivityResult from parcelable editor

### ISSUE THREAD

**Issue by tsiemens** [tsiemens/pathfinder-toolkit#8]
Affects version: 2.0
Device: Galaxy S4 Mini
Android Version: 4.2

Report from user:

App crashed after confirming changes to skill points.

```
java.lang.RuntimeException: Unable to resume activity {com.lateensoft.pathfinder.toolkit/com.lateensoft.pathfinder.toolkit.PTMainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=android:fragment:0, request=0, result=-1, data=Intent { (has extras) }} to activity {com.lateensoft.pathfinder.toolkit/com.lateensoft.pathfinder.toolkit.PTMainActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2835)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2864)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2309)
at android.app.ActivityThread.access$700(ActivityThread.java:152)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:176)
at android.app.ActivityThread.main(ActivityThread.java:5299)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=android:fragment:0, request=0, result=-1, data=Intent { (has extras) }} to activity {com.lateensoft.pathfinder.toolkit/com.lateensoft.pathfinder.toolkit.PTMainActivity}: java.lang.NullPointerException
at android.app.ActivityThread.deliverResults(ActivityThread.java:3415)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2822)
... 12 more
Caused by: java.lang.NullPointerException
at com.lateensoft.pathfinder.toolkit.views.character.PTCharacterFeatsFragment.onActivityResult(PTCharacterFeatsFragment.java:108)
at android.app.Activity.dispatchActivityResult(Activity.java:5519)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3411)
... 13 more
```

**Comment by tsiemens** [comment]
Unsure at this point why this is happening, as I couldn't reproduce. Added some extra null checks. Will need to see if more crash reports come in.
